### ISSUE TITLE
rosrun command not found

### ISSUE THREAD

**Issue by eehantiming** [seeeheng/deploy-slim#1]
Hi seeeheng, i am not able to rosrun in the container and this can be fixed by installing `ros-melodic-rosbash`. maybe you want to add this to the dockerfile?
Also, in the readme i believe you have an extra ``` after the 8a line.
Thanks!

**Comment by sihengt** [comment]
I'm not sure if I encounter the same error with ros-melodic-rosbash - let me check on a fresh build. Thanks for pointing it out. I've also removed the ``` after 8a.
